### ISSUE TITLE
Error with default config

### ISSUE THREAD

**Issue by cyberdie** [amcolash/MMM-GoogleFit#1]
First of all, thanks for this module.
With default config, i'm receiving the following error whe starting MagicMirror.

_WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'jsonfile'_

And

_Whoops! There was an uncaught exception...
{ [Error: Cannot find module 'jsonfile'] code: 'MODULE_NOT_FOUND' }_

I'm on a Pi Zero with Server only and over 10 working modules.
Looks like node_helper has some issue

**Comment by amcolash** [comment]
Huh that is odd, I can look into that today. Can you quick go into the
module folder and send a list of files there?

It should have something called `jsonfile.js`. thanks!

**Comment by cyberdie** [comment]
Yes, it is.

192 -rw-r--r-- 1 pi pi 194851 Jan 14 12:05 highcharts.js
  4 -rw-r--r-- 1 pi pi   2838 Jan 14 12:05 **jsonfile.js**
  4 -rw-r--r-- 1 pi pi   1071 Jan 14 12:05 LICENSE
  8 -rw-r--r-- 1 pi pi   6525 Jan 14 12:05 MMM-GoogleFit.js
  8 -rw-r--r-- 1 pi pi   5198 Jan 14 12:05 node_helper.js
  4 -rw-r--r-- 1 pi pi   1075 Jan 14 12:05 notes
  4 -rw-r--r-- 1 pi pi   1046 Jan 14 12:09 npm-debug.log
  4 -rw-r--r-- 1 pi pi   3585 Jan 14 12:05 README.md
  4 drwxr-xr-x 2 pi pi   4096 Jan 14 12:05 screenshots
  0 -rw-r--r-- 1 pi pi      0 Jan 14 12:05 style.css

**Comment by amcolash** [comment]
Can I have you run `node -v` and give the output? I'm running nose on my
laptop and pi 2 without issues so maybe I've got a newer/older version and
something changed with requiring modules between versions

**Comment by cyberdie** [comment]
node version is v4.2.1
But rememeber i'm running on pi zero

**Comment by amcolash** [comment]
Yeah, I am running 8.9.4, so I am assuming node has changed a bit since. Just pushed a new version that explicitly references that file in `node_helper`, can you try it out?

**Comment by cyberdie** [comment]
Yes, it woks!

But now, the module shows the following instead of device code:

_**Error Getting Auth**_

**Comment by amcolash** [comment]
Hmm, getting closer! Can I have you pull again and send along the entire log that it spits out? I added in some debug logging which should help us out.

**Comment by amcolash** [comment]
Please send the log to amcolash@gmail.com, since it will contain some sensitive info (to be displayed in comments). None of it can be used to get into your account mind you, just better if it isn't totally public.

**Comment by amcolash** [comment]
Also, out of curiosity I just installed node 4.2.1 temporarily and was not seeing any auth issues. Not entirely sure what the issue could be but it sure is interesting.

**Comment by cyberdie** [comment]
Hi again @amcolash , sorry for my late response.
Looks like module works after authentication code is validated but does NOT show any data.
Only:
_Authenticated. Loading Data_

I'll pull the debug version and send you the log ASAP.

**Comment by amcolash** [comment]
Did you ever get the logs? Just want to make sure I didn't miss them.

**Comment by cyberdie** [comment]
Where are the debug logs located when running on "node server only" mode?

**Comment by amcolash** [comment]
In your terminal, it should just spit out a bunch of stuff. Check that `node_helper` has a line with `debug: true`. If not, just set that from `false` to `true`. Then just copy/paste what is displayed when you type `$ node serveronly`

**Comment by cyberdie** [comment]
Sorry for the late response. I've been too busy.
The issue is still there but sometimes it works when browsing the mirror with chrome from my PC.
In the mirror never worked. Stays Loading Data forever.
I think it is something regarded to electron and Midori.
Debug log sent.

**Comment by amcolash** [comment]
Hi no worries about the late response - I have been pretty busy too! Looks like your mirror was able to successfully authenticate from the logs that I saw. I apparently missed the logging for getting stat data, so it seems something is wrong with the actual pulling from google fit on your end. I have updated the repo to have verbose logging for acquiring stats. Can I have you pull again and again make sure that debugging is enabled in `node_helper.js`? Thanks, send along the logs when you get a chance.

**Comment by cyberdie** [comment]
Maybe this?

** Message: console message:
http://localhost:8080/modules/MMM-GoogleFit//MMM-GoogleFit.js @314:
ACCESS_TOKEN_BODY

** Message: console message:
http://localhost:8080/modules/MMM-GoogleFit//MMM-GoogleFit.js @315: [object
Object]

** Message: console message:
http://localhost:8080/modules/MMM-GoogleFit//MMM-GoogleFit.js @314: STATS

** Message: console message:
http://localhost:8080/modules/MMM-GoogleFit//MMM-GoogleFit.js @315: [object
Object]

*** Message: console message:
http://localhost:8080/modules/MMM-GoogleFit//MMM-GoogleFit.js
<http://localhost:8080/modules/MMM-GoogleFit//MMM-GoogleFit.js> @68:
TypeError: undefined is not a function (evaluating
'Number.parseFloat(bucket.startTimeMillis)')*

**Comment by amcolash** [comment]
That looks like the bug there! Something is going wrong with the parsing of the returned data from google. It is odd that `Number.parseFloat` is not found on your browser. I am pretty sure that is standard JS. I will check out if Midori has something to do with this. Can also change those functions to something a bit more "compatible" if needed.

**Comment by cyberdie** [comment]
Yes, it must be a browser problem because browsing the mirror with chrome
on my mobile phone worked as expected.
Se attached screenshot

[image: Inline image 1]

**Comment by amcolash** [comment]
I installed midori and found a handful of issues. Seems like it is running a stricter and simpler js engine than chrome/ff/etc. I , just pushed a commit that you can pull. It fixed all issues that I was seeing in my version of midori. Let me know if that fixes things up!

**Comment by cyberdie** [comment]
Hi Andrew, thanks a lot!
With your last changes, the validation process works like a charm and info
is updating regularly.
kudos for you!

Regards
Diego

**Comment by amcolash** [comment]
Thanks for helping out with finding these few bugs. Glad to make things compatible on the pi zero. Good to know that Midori enforces some stricter stuff. Enjoy the module and make a ticket if you'd like any new features.
