### ISSUE TITLE
no longer showing my logged daily weight

### ISSUE THREAD

**Issue by justjim1220** [amcolash/MMM-GoogleFit#13]
After last update, I haven't been able to get my daily weights to show on the module...

I've tried pretty much everything I can figure in attempts to get it to work. But, everything I have tried will not show them. 

Can someone help me with this?

Is anyone else having the same problem?

Thanks in advance!!!

**Comment by amcolash** [comment]
Hm, this might be related to the new month bug floating around, #9 I think... Let me know if it continues to happen.

**Comment by amcolash** [comment]
Please update to the latest to fix the end of month bug:
```
$ cd MagicMirror/modules/MMM-GoogleFit
$ git pull
```
