### ISSUE TITLE
Show the last 7 days instead of week by week

### ISSUE THREAD

**Issue by poloking** [amcolash/MMM-GoogleFit#15]
Love this module, but it would be great if it could show the last 7 days rather than the current week since about half of the time half of the circles show no data.

**Comment by amcolash** [comment]
I updated the module to support this feature. Can you please test to see if this is what you were looking for?

Update the module:
```
$ cd MagicMirror
$ cd modules/MMM-GoogleFit
$ git pull
```

Add the following to your config:
```
config: {
    ...
    lastSevenDays: true
}
```

**Comment by poloking** [comment]
Thanks for such a quick response. This wasn't exactly what I was looking though I can see why someone might find it interesting. 

Maybe I didn't explain properly. 
Today is saturday1st sept. So I would like to see the data for today, yesterday, day before, day before that, etc., etc.

What I think you have added is to show the data for the previous full week. Or at least that is what it shows for me.

**Comment by amcolash** [comment]
I see. I think I did exactly what you did but in reverse order. In my case I was assuming that if today is Monday, you wanted it to show T W T F S S M - where Monday is the last day shown at the edge. I could reverse the list so that Monday is the closest and Tuesday is the furthest. I.E. M S S F T W T.

**Comment by poloking** [comment]
Apologies. I went back and reset everything. And it works as expected already.

Thank you for this great new feature.

**Comment by amcolash** [comment]
Awesome, glad to hear. I am adding a new option to reverse the ordering of the days, just in case since it is pretty simple anyways!

If you are interested:
```
config: {
    ...
    reverseOrder: true
}
```
