### ISSUE TITLE
Error Getting Auth

### ISSUE THREAD

**Issue by SilentFoxy1** [amcolash/MMM-GoogleFit#16]
I have just installed it I did connect my gmail to this and have the app on my phone. While the google fit module loading for first time I did a reboot on my raspberry and now I have this error message "Error Getting Auth Stats Error"

**Comment by SilentFoxy1** [comment]
I have just reinstalled it and its stuck on Authenticated,Loading Data... for like 10 minutes or so

**Comment by snowthrills** [comment]
Same issue, installed and allowed Auth moments ago.

**Comment by snowthrills** [comment]
@amcolash I turned on debug and have some logs to share but since they contain client secrets I don't want to put in the public eye.  Please advise how best to share directly with you. The last post in the output is :

> read: [Function],
  body:
   { error:
      { errors: [Array],
        code: 400,
        message: 'datasource not found: derived:com.google.weight:com.google.android.gms:merge_weight' } } }
body
{ error:
   { errors: [ [Object] ],
     code: 400,
     message: 'datasource not found: derived:com.google.weight:com.google.android.gms:merge_weight' } }

**Comment by amcolash** [comment]
Interesting. Can I have you change your `config.js` to have the following option: `displayWeight: false` under the `config` section? It looks like there might be an issue polling google fit if you have never added weight data.

**Comment by amcolash** [comment]
If that is the case, I can change the default of that option for new users and it is an opt-in for showing weights since not all users may have them. Seems that the google api is a little flakey :(

**Comment by SilentFoxy1** [comment]
Mine got fixed by it self idk how XD

**Comment by amcolash** [comment]
@snowthrills you can send me an email (listed on github profile).

closing this issue for now as I it seems that things are working for at least some people and I need more info to investigate
