### ISSUE TITLE
Borders and padding on bottom of module

### ISSUE THREAD

**Issue by TheKyleJohnson90** [amcolash/MMM-GoogleFit#18]
When using a border, the labels on the bottom will be displayed on the border, instead of above.

**Comment by amcolash** [comment]
I think I fixed it. Please let me know if things work after upgrading the module

```
cd MagicMirror/modules/MMM-GoogleFit
git pull
```

**Comment by TheKyleJohnson90** [comment]
You should only need to accept my pull request. I have already developed the fix.

**Comment by amcolash** [comment]
So sorry, I didn't realize you had a pr open! I found the same solution in the end, whoops! Thank you for that. I like yours better though, so I will merge that when I get a chance
