### ISSUE TITLE
Changing start of the week

### ISSUE THREAD

**Issue by wqwdpxd** [amcolash/MMM-GoogleFit#2]
Hi,

Is it possible to change the start of the week to Monday? 
Also, sorry for opening an issue for this, but I couldn't find the option anywhere.

Best regards

**Comment by amcolash** [comment]
No worries. I use Sunday-Saturday calendar personally so I never had a need for this.

**Comment by amcolash** [comment]
Should be all set with dec84d5adb7a04ae4dc39082555ae8a758d17492. Could I ask you to check if that is what you are looking for? I tested on my end and things seemed to be working correctly. Just add `startOnMonday: true` to your config - mentioned in the `README` as well.

**Comment by wqwdpxd** [comment]
Thank you so much for such a quick response and implementation. It's working perfectly.

Best regards, Dominik

**Comment by amcolash** [comment]
👍
