### ISSUE TITLE
Authentication wrong code format

### ISSUE THREAD

**Issue by fry0815** [amcolash/MMM-GoogleFit#20]
Hi,

i get the wrong code format for the authentification. My code format is XXX-XXX-XXX instead of XXXX-XXXX.

What can i do?

Thanks.

**Comment by amcolash** [comment]
Hm, that is interesting - Google must have changed their device authentication. I can probably take a look this weekend.

**Comment by fry0815** [comment]
I do nothing and tryed again, now it works. I close the issue. Thanks :)

**Comment by amcolash** [comment]
I also noticed this the other day. Looks like a restart of the MM fixed it. If it becomes a recurring issue I will re-open!
