### ISSUE TITLE
Shocking news that support has stopped

### ISSUE THREAD

**Issue by alomar-mac** [amcolash/MMM-GoogleFit#29]
I am sad to read the latest update from the developer, the program (GoogleFit) module has stopped supporting, it is sad news

any how We wish you well

**Comment by amcolash** [comment]
I have been quite busy in life and if you look at the commits, no history has happened in a year on this project. Happy to merge MRs and/or give repo rights to others. Feel free to fork otherwise. As of now, this was a fun project and still works fine for my basic needs.
