### ISSUE TITLE
Stats Error

### ISSUE THREAD

**Issue by amcolash** [amcolash/MMM-GoogleFit#4]
From the forums, [link](https://forum.magicmirror.builders/post/36101):

> StacheEnthusiast 2/21/2018 6:10 PM
>
> I’m getting an auth error, “stats error”. I’ve followed the steps and MMM-GoogleFit shows up in my google apps with permissions. Any ideas?

**Comment by amcolash** [comment]
Firstly, can you tell me a bit about your setup? Device running MM, if you are using electron or an external browser, what version of node you are running (`node --version`), any other interesting or unique things.

Secondly, there is a bunch of built in logging that can help us get more info on the situation. You will need to edit the file `MMM-GoogleFit/node_helper.js`, change the line at the top that says:
`debug: false,` to `debug: true,`

Then, start up your sever via `$ cd MagicMirror`, `$ node serveronly` and use a web browser to go to the page listed (should be `http://localhost:8080`). You should get a bunch of stuff in your terminal - can you upload/paste that here?

Note: since this is a public repo anyone can see what you paste here. The only permission is for reading from google fit. If you would prefer, you can send along the info to amcolash@gmail.com and I can check the logs without them being public - your call. Otherwise you can send the info and then revoke access on your google profile so you will need to re-login, but will revoke access from that auth key.

**Comment by amcolash** [comment]
Never got any response. If there are other issues like this we can re-open the issue.

**Comment by kolbyjack** [comment]
I'm also seeing this after installing.  getStat's POST /fitness/v1/users/me/dataset:aggregate is always met with an error 500:

{ error: { errors: [ [Object] ], code: 500, message: 'Backend Error' } }

While the fit api docs don't cover it, the drive api says that the app should use exponential backoff in this case, and that the app's quota should be checked on the google api console.  Could it be that the module has just become popular enough that there are too many requests being sent?

**Comment by kolbyjack** [comment]
Nevermind, I created my own token and am still getting 500s

**Comment by kolbyjack** [comment]
I figured it out, my only fit data comes from the fit app on my phone, so I don't have any com.google.weight data to aggregate by.  If I change the aggregateBy to just

> "aggregateBy": [{
>   "dataSourceId": "derived:com.google.step_count.delta:com.google.android.gms:estimated_steps"
> }],

like the one in the api example, it works.
