### ISSUE TITLE
error on start with monday

### ISSUE THREAD

**Issue by apm1007** [amcolash/MMM-GoogleFit#6]
Module turns on saturday night to monday. Sunday isnt displayed.

**Comment by amcolash** [comment]
Sorry about the really late reply. I had quite a busy week. The start on monday config should now work correctly. You will need to update your module:
`$ cd MagicMirror`
`$ cd modules/MMM-GoogleFit`
`$ git pull`

**Comment by apm1007** [comment]
No Problem. Thank You very much. Pushed The Update Yesterday. Will have A
Look at IT.

Andrew McOlash <notifications@github.com> schrieb am So., 11. März 2018,
21:38:
