### ISSUE TITLE
After new installation google fit not start

### ISSUE THREAD

**Issue by FreddanB** [amcolash/MMM-GoogleFit#7]
![skarmklipp](https://user-images.githubusercontent.com/30792107/39521105-735f1ad2-4e0d-11e8-9ae7-3f8579776760.PNG)
what is this ?

**Comment by FreddanB** [comment]
Starting MagicMirror: v2.3.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-GoogleFit
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ...
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-GoogleFit
MMM-GoogleFit helper started...
{ http_parser: '2.8.0',
  node: '9.11.1',
  v8: '6.2.414.46-node.23',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  napi: '3',
  openssl: '1.0.2o',
  icu: '61.1',
  unicode: '10.0',
  cldr: '33.0',
  tz: '2018c' }
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...

Ready to go! Please point your browser to: http://localhost:8080
Whoops! There was an uncaught exception...
{ Error: listen EADDRINUSE 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1346:14)
    at listenInCluster (net.js:1387:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1502:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:72:10)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080 }
MagicMirror will not quit, but it might be a good idea to check why this happene                                                                      d. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://gi                                                                      thub.com/MichMich/MagicMirror/issues

**Comment by amcolash** [comment]
Looks like an issue with the core magic mirror server trying to start twice (assuming you don't have anything else pointed to Port 8080). I have a feeling things just got worse then by the time the module tried to initialize. I can definitely dig a bit deeper when I get a chance.

**Comment by anubhavaich** [comment]
The same is happening with me. Fresh installed MM and still the same.

**Comment by FreddanB** [comment]
Yes fresh installed MM and Google-Fit are first module to be installed, try with 3 different RP3 and different SD-card.

**Comment by amcolash** [comment]
Could one of you post the relevant section of your `config.js` file? Thanks!

**Comment by fatcatcgo** [comment]
US English(I'm in Texas y'all) version.  Was working until the last week or so.  No changes or updates that I am aware.

Just looked to tackle this this today thinking it was padding or something but nope.  No idea.

**Comment by justjim1220** [comment]
Mine is doing the same thing! Did a fresh install as well - No changes

![screenshot 10](https://user-images.githubusercontent.com/27590633/39606312-6f68a8d8-4efa-11e8-919d-eaad525ccd54.png)

![screenshot_20180503-175113](https://user-images.githubusercontent.com/27590633/39606484-54a90848-4efb-11e8-81c6-581abfbff29f.png)

and I don't have 0 days.

and I start on Sunday.

Any ideas how to fix this would be great!

**Comment by justjim1220** [comment]
Working correctly today... 😏😏😏

**Comment by fatcatcgo** [comment]
Yes,  Very odd.  Working as normal now.

**Comment by FreddanB** [comment]
Same here working. Case closed

**Comment by amcolash** [comment]
Dupe of #9.

Check out the explanation there. Update is pushed as well. Run `$ cd MagicMirror/modules/MMM-GoogleFit`, `$ git pull`.
